### ISSUE TITLE
分类使用resnet，inception，densenet都不收敛，我也加入dropout试了，不收敛。vgg收敛了

### ISSUE THREAD

**Issue by 646677064** [wikke/Tianchi-Medical-LungTumorDetect#3]
谢谢你的代码哦。我是用的luna2016数据集。分类使用resnet，inception，densenet不收敛，加入dropout试了也不收敛，请问你怎么做的呀？

**Comment by wikke** [comment]
resnet，inception我做得不是很深入，建议你参考更多实现，或者直接官方实现尝试一下。densenet多些。不过你也需要考虑下learning rate等问题，其次还有BN

**Comment by 646677064** [comment]
嗯的，谢谢
